# Generated by Django 3.1 on 2020-09-06 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=30)),
                ('away_team', models.CharField(max_length=30)),
                ('referee', models.CharField(max_length=30)),
                ('home_team_ht_goals', models.IntegerField(default=0)),
                ('away_team_ht_goals', models.IntegerField(default=0)),
                ('home_team_ft_goals', models.IntegerField(default=0)),
                ('away_team_ft_goals', models.IntegerField(default=0)),
                ('home_team_shots', models.IntegerField(default=0)),
                ('away_team_shots', models.IntegerField(default=0)),
                ('home_team_shots_on_target', models.IntegerField(default=0)),
                ('away_team_shots_on_target', models.IntegerField(default=0)),
                ('result', models.CharField(max_length=1)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.season')),
            ],
        ),
    ]
